[build]
  base = "project- app - glowupstudio"
  publish = "project- app - glowupstudio/dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
